### ISSUE TITLE
When will the code be avalible? 

### ISSUE THREAD

**Issue by Rotoslider** [kevin2431/ECTLO#1]
I have a Livox Horizon that I would love to use with your code. How do I go about acquiring the code?

**Comment by kevin2431** [comment]
Thank you for following our work. We plan to release binary lib for testing once the paper is accepted.

**Comment by kevin2431** [comment]
> I have a Livox Horizon that I would love to use with your code. How do I go about acquiring the code?
Thank you for following our work. We plan to release binary lib for testing once the paper is accepted.
