### ISSUE TITLE
Test data format

### ISSUE THREAD

**Issue by chengwei0427** [kevin2431/ECTLO#2]
Hi， @kevin2431 
Nice work!
I'm wondering what is the format of the test data, how to convert to a normal format?

```
namespace liovx_ros{
    struct Eigen_ALIGN16 Point
    {
         PCLL_ADD_POINT4D
         PCL_ADD_INTENSITY;
         float time;
         uint16_t ring;
         uint16_t tag;
          EIGEN_MAKE_ALIGNED_OPERATOR_NEW
       };
}
```
I used the above data format and there was a conversion exception.

**Comment by kevin2431** [comment]
Thanks for your attention!
The dataset is directly recorded using [livox_ros_driver](https://github.com/Livox-SDK/livox_ros_driver). The message format is "livox_ros_driver/CustomMsg", which is
```
uint32 offset_time      # offset time relative to the base time
float32 x               # X axis, unit:m
float32 y               # Y axis, unit:m
float32 z               # Z axis, unit:m
uint8 reflectivity      # reflectivity, 0~255
uint8 tag               # livox tag
uint8 line              # laser number in lidar
```

**Comment by kevin2431** [comment]
> Thanks for your attention! The dataset is directly recorded using [livox_ros_driver](https://github.com/Livox-SDK/livox_ros_driver). The message format is "livox_ros_driver/CustomMsg", which is
> 
> ```
> uint32 offset_time      # offset time relative to the base time
> float32 x               # X axis, unit:m
> float32 y               # Y axis, unit:m
> float32 z               # Z axis, unit:m
> uint8 reflectivity      # reflectivity, 0~255
> uint8 tag               # livox tag
> uint8 line              # laser number in lidar
> ```

As for the ZJU-M*.bag, it is recorded in
```
float32 x               # X axis, unit:m
float32 y               # Y axis, unit:m
float32 z               # Z axis, unit:m
float32 intensity         # the value is reflectivity, 0.0~255.0
uint8 tag               # livox tag
uint8 line              # laser number in lidar
